
name: Deploy to S3
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
        - name: configure aws credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            role-to-assume: arn:aws:iam::569625835669:role/GithubActionsOIDC-Role-4K7A9WDUP36B
            role-duration-seconds: 900 # the ttl of the session, in seconds.
            aws-region: us-east-1 # use your region here.
        - uses: actions/checkout@v2

        - name: Setup hugo
          uses: peaceiris/actions-hugo@v2
          with:
            hugo-version: 'latest'

        - name: Build
          run: hugo --buildDrafts --gc --verbose --minify

        - name: Deploy
          uses: reggionick/s3-deploy@v3
          with:
            folder: public
            bucket: ${{ secrets.S3_BUCKET }}
            bucket-region: ${{ secrets.S3_BUCKET_REGION }}
            dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
            invalidation: /
            delete-removed: true
            no-cache: true
            private: true